apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "SuperTest"
  annotations:
    github.com/project-slug: Platform-Squad-Infra/Stream-Value-Green
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/stream-squad-red
  lifecycle: experimental
  providesApis: [example-grpc-api, example-grpc-api-2]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api-2
spec:
  type: grpc
  lifecycle: experimental
  owner: group:default/stream-squad-red
  definition: |
    syntax = "proto3";

    service Exampler1 {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message Example1Message {
      string example = 1;
    };

