apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "SuperTest"
  annotations:
    github.com/project-slug: Platform-Squad-Infra/Stream-Value-Green
spec:
  type: service
  owner: group:Platform-Squad-Infra/Stream-Value-Green
  lifecycle: experimental
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };

