site_name: 'example-docs'

plugins:
  - techdocs-core

nav:
  - Home: index.md
  # For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
      - Architecture overview: 'overview/architecture-overview.md'

