# A first Worklow to play around with the editor
name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs: 
  first_job:
    name: My first Job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
            echo "Hello best World from ${{github.actor}}."
            echo "Current branch ${{github.ref}}."
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - run: tree
      
        
      
        
        
      
    
  
    
  
    
    
      
